"""Research-only discovery run manager foundation."""

from __future__ import annotations

from tradingbotsuite.research_discovery.runner import DiscoveryRunResult, run_discovery
from tradingbotsuite.research_discovery.ablation_matrix import (
    AblationComparisonSpec,
    PerpFilterAblationArtifactResult,
    PerpFilterAblationMatrixResult,
    PerpFilterAblationMatrixSpec,
    build_perp_filter_ablation_matrix,
    write_perp_filter_ablation_artifacts,
)
from tradingbotsuite.research_discovery.benchmark import (
    DISCOVERY_BENCHMARK_TIERS,
    DiscoveryBenchmarkResult,
    write_discovery_benchmark_report,
)
from tradingbotsuite.research_discovery.candidate_pack_bridge import (
    DISCOVERY_CANDIDATE_PACK_BRIDGE_VERSION,
    DiscoveryCandidatePackBridgeArtifactResult,
    DiscoveryCandidatePackBridgeResult,
    evaluate_discovery_candidate_pack_eligibility,
    validate_discovery_candidate_pack_bridge_manifest,
    write_discovery_candidate_pack_eligibility,
)
from tradingbotsuite.research_discovery.discovery_lead_materialization import (
    DISCOVERY_LEAD_MATERIALIZATION_MANIFEST_VERSION,
    DISCOVERY_LEAD_MATERIALIZATION_VERSION,
    DiscoveryLeadMaterializationArtifactResult,
    DiscoveryLeadMaterializationResult,
    DiscoveryLeadMaterializationSpec,
    materialize_discovery_leads_from_manifest,
    validate_discovery_lead_materialization_manifest,
    write_discovery_lead_materialization_artifacts,
)
from tradingbotsuite.research_discovery.discovery_lead_replay import (
    DISCOVERY_LEAD_REPLAY_SPEC_VERSION,
    DISCOVERY_REPLAY_ENTRY_SIGNAL_MANIFEST_VERSION,
    DISCOVERY_REPLAY_ENTRY_SIGNAL_VERSION,
    DiscoveryLeadReplaySpecArtifactResult,
    DiscoveryLeadReplaySpecResult,
    DiscoveryReplayEntrySignalArtifactResult,
    DiscoveryReplayEntrySignalResult,
    aggregate_discovery_replay_entry_signals,
    build_discovery_lead_replay_spec,
    validate_discovery_replay_entry_signal_manifest,
    write_discovery_lead_replay_spec,
    write_discovery_replay_entry_signal_artifacts,
)
from tradingbotsuite.research_discovery.replay_overlay_preflight import (
    REPLAY_OVERLAY_CYCLE_PREFLIGHT_POLICY,
    REPLAY_OVERLAY_CYCLE_PREFLIGHT_VERSION,
    REPLAY_OVERLAY_CYCLE_SPEC_DRAFT_POLICY,
    REPLAY_OVERLAY_CYCLE_SPEC_DRAFT_VERSION,
    ReplayOverlayCyclePreflightArtifactResult,
    ReplayOverlayCyclePreflightResult,
    ReplayOverlayCycleSpecDraftArtifactResult,
    ReplayOverlayCycleSpecDraftResult,
    build_replay_overlay_cycle_spec_drafts,
    preflight_replay_overlay_cycle_specs,
    validate_replay_overlay_cycle_preflight_manifest,
    validate_replay_overlay_cycle_spec_draft_manifest,
    write_replay_overlay_cycle_preflight_artifacts,
    write_replay_overlay_cycle_spec_draft_artifacts,
)
from tradingbotsuite.research_discovery.exit_lab import (
    DiscoveryExitLabArtifactResult,
    DiscoveryExitLabResult,
    DiscoveryExitLabSpec,
    ExitLabComparisonSpec,
    build_discovery_exit_lab,
    discovery_entry_lead_evidence_sha256,
    write_discovery_exit_lab_artifacts,
)
from tradingbotsuite.research_discovery.feature_sets import (
    DiscoveryFeatureColumnSetManifest,
    load_feature_column_set_manifest,
)
from tradingbotsuite.research_discovery.hmm_materialization import (
    HmmMaterializationArtifactResult,
    HmmMaterializationResult,
    HmmMaterializationSpec,
    materialize_split_safe_hmm_regimes,
    write_hmm_materialization_artifacts,
)
from tradingbotsuite.research_discovery.knn_study import (
    KnnStudyArtifactResult,
    KnnStudyResult,
    KnnStudySpec,
    materialize_regime_local_knn_predictions,
    write_knn_study_artifacts,
)
from tradingbotsuite.research_discovery.multiple_testing import (
    DiscoveryMultipleTestingArtifactResult,
    DiscoveryMultipleTestingResult,
    DiscoveryMultipleTestingSpec,
    build_discovery_multiple_testing_report,
    build_discovery_multiple_testing_report_from_manifest,
    write_discovery_multiple_testing_artifacts,
)
from tradingbotsuite.research_discovery.validation_floors import (
    DiscoveryValidationFloorArtifactResult,
    DiscoveryValidationFloorResult,
    DiscoveryValidationFloorSpec,
    blocker_registry_payload,
    build_discovery_validation_floor_report,
    build_discovery_validation_floor_report_from_manifest,
    registered_blocker_codes,
    write_discovery_validation_floor_artifacts,
)
from tradingbotsuite.research_discovery.strategy_integration import (
    DiscoveryStrategyAccountingArtifactResult,
    DiscoveryStrategyAccountingResult,
    account_hmm_knn_local_analog_strategy,
    write_strategy_accounting_artifacts,
)
from tradingbotsuite.research_discovery.spec import DiscoveryRunSpec

__all__ = [
    "DiscoveryFeatureColumnSetManifest",
    "DiscoveryExitLabArtifactResult",
    "DiscoveryExitLabResult",
    "DiscoveryExitLabSpec",
    "DiscoveryStrategyAccountingArtifactResult",
    "DiscoveryStrategyAccountingResult",
    "ExitLabComparisonSpec",
    "HmmMaterializationArtifactResult",
    "HmmMaterializationResult",
    "HmmMaterializationSpec",
    "KnnStudyArtifactResult",
    "KnnStudyResult",
    "KnnStudySpec",
    "AblationComparisonSpec",
    "DiscoveryRunResult",
    "DiscoveryRunSpec",
    "DiscoveryMultipleTestingArtifactResult",
    "DiscoveryMultipleTestingResult",
    "DiscoveryMultipleTestingSpec",
    "DiscoveryLeadMaterializationArtifactResult",
    "DiscoveryLeadMaterializationResult",
    "DiscoveryLeadMaterializationSpec",
    "DiscoveryLeadReplaySpecArtifactResult",
    "DiscoveryLeadReplaySpecResult",
    "DiscoveryReplayEntrySignalArtifactResult",
    "DiscoveryReplayEntrySignalResult",
    "ReplayOverlayCyclePreflightArtifactResult",
    "ReplayOverlayCyclePreflightResult",
    "ReplayOverlayCycleSpecDraftArtifactResult",
    "ReplayOverlayCycleSpecDraftResult",
    "DiscoveryValidationFloorArtifactResult",
    "DiscoveryValidationFloorResult",
    "DiscoveryValidationFloorSpec",
    "DiscoveryBenchmarkResult",
    "DiscoveryCandidatePackBridgeArtifactResult",
    "DiscoveryCandidatePackBridgeResult",
    "DISCOVERY_CANDIDATE_PACK_BRIDGE_VERSION",
    "DISCOVERY_LEAD_MATERIALIZATION_MANIFEST_VERSION",
    "DISCOVERY_LEAD_MATERIALIZATION_VERSION",
    "DISCOVERY_LEAD_REPLAY_SPEC_VERSION",
    "DISCOVERY_REPLAY_ENTRY_SIGNAL_MANIFEST_VERSION",
    "DISCOVERY_REPLAY_ENTRY_SIGNAL_VERSION",
    "REPLAY_OVERLAY_CYCLE_PREFLIGHT_POLICY",
    "REPLAY_OVERLAY_CYCLE_PREFLIGHT_VERSION",
    "REPLAY_OVERLAY_CYCLE_SPEC_DRAFT_POLICY",
    "REPLAY_OVERLAY_CYCLE_SPEC_DRAFT_VERSION",
    "DISCOVERY_BENCHMARK_TIERS",
    "PerpFilterAblationArtifactResult",
    "PerpFilterAblationMatrixResult",
    "PerpFilterAblationMatrixSpec",
    "account_hmm_knn_local_analog_strategy",
    "aggregate_discovery_replay_entry_signals",
    "build_discovery_lead_replay_spec",
    "build_discovery_exit_lab",
    "build_discovery_multiple_testing_report",
    "build_discovery_multiple_testing_report_from_manifest",
    "blocker_registry_payload",
    "build_discovery_validation_floor_report",
    "build_discovery_validation_floor_report_from_manifest",
    "build_perp_filter_ablation_matrix",
    "build_replay_overlay_cycle_spec_drafts",
    "discovery_entry_lead_evidence_sha256",
    "load_feature_column_set_manifest",
    "materialize_split_safe_hmm_regimes",
    "materialize_regime_local_knn_predictions",
    "materialize_discovery_leads_from_manifest",
    "preflight_replay_overlay_cycle_specs",
    "run_discovery",
    "evaluate_discovery_candidate_pack_eligibility",
    "registered_blocker_codes",
    "write_hmm_materialization_artifacts",
    "write_knn_study_artifacts",
    "validate_discovery_candidate_pack_bridge_manifest",
    "validate_discovery_lead_materialization_manifest",
    "validate_discovery_replay_entry_signal_manifest",
    "validate_replay_overlay_cycle_preflight_manifest",
    "validate_replay_overlay_cycle_spec_draft_manifest",
    "write_discovery_candidate_pack_eligibility",
    "write_discovery_exit_lab_artifacts",
    "write_discovery_lead_replay_spec",
    "write_discovery_multiple_testing_artifacts",
    "write_discovery_lead_materialization_artifacts",
    "write_discovery_replay_entry_signal_artifacts",
    "write_replay_overlay_cycle_preflight_artifacts",
    "write_replay_overlay_cycle_spec_draft_artifacts",
    "write_discovery_validation_floor_artifacts",
    "write_discovery_benchmark_report",
    "write_perp_filter_ablation_artifacts",
    "write_strategy_accounting_artifacts",
]
